/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.wellington.apresentacao;

import br.edu.ifnmg.wellington.entidade.Usuario;
import br.edu.ifnmg.wellington.negocio.UsuarioBO;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;
import sun.security.provider.VerificationProvider;

/**
 *
 * @author Were
 */
public class ListagemUsuarios extends javax.swing.JFrame {

    /**
     * Creates new form ListagemUsuarios
     */
    private TelaDeUsuarios telaDeUsuarios;   
    private List<Usuario> usuarios;
    private List<String> gruposTrabalho;
  
    int estadoTela = 0;

    public ListagemUsuarios() throws SQLException {
        initComponents();
        this.carregarTabelaDeUsuarios();
    }    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaUsuarios = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        btnEditarUsuario = new javax.swing.JButton();
        btnNovoUsuario = new javax.swing.JButton();
        btnExcluirUsuario = new javax.swing.JButton();
        btnCargos = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Listagem de Usuários");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Usuários"));

        tabelaUsuarios.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        tabelaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelaUsuarios);

        jScrollPane4.setViewportView(jList1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnEditarUsuario.setText("Editar");
        btnEditarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarUsuarioActionPerformed(evt);
            }
        });

        btnNovoUsuario.setText("Novo");
        btnNovoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoUsuarioActionPerformed(evt);
            }
        });

        btnExcluirUsuario.setText("Excluir");
        btnExcluirUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirUsuarioActionPerformed(evt);
            }
        });

        btnCargos.setText("Cargos");
        btnCargos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargosActionPerformed(evt);
            }
        });

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(btnNovoUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditarUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluirUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCargos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnVoltar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditarUsuario)
                    .addComponent(btnExcluirUsuario)
                    .addComponent(btnNovoUsuario)
                    .addComponent(btnCargos)
                    .addComponent(btnVoltar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoUsuarioActionPerformed
        if (this.telaDeUsuarios == null) {
            this.telaDeUsuarios = new TelaDeUsuarios(this);
        }
        this.telaDeUsuarios.setVisible(true);
        this.telaDeUsuarios.toFront();
       
    }//GEN-LAST:event_btnNovoUsuarioActionPerformed

    private void btnEditarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarUsuarioActionPerformed
        this.estadoTela = 1;
        this.editarUsuario();
    }//GEN-LAST:event_btnEditarUsuarioActionPerformed

    private void btnExcluirUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirUsuarioActionPerformed
        this.excluirUsuario();
        this.jList1.setListData(new Vector());
    }//GEN-LAST:event_btnExcluirUsuarioActionPerformed

    private void btnCargosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargosActionPerformed
        this.exibeGrupoTrabalho();
    }//GEN-LAST:event_btnCargosActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
       this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

     public void carregarTabelaDeUsuarios() throws SQLException {
        UsuarioBO usuarioBO = new UsuarioBO();
        this.usuarios = usuarioBO.buscarTodosUsuarios();
        ModeloTabelaUsuarios modelo = new ModeloTabelaUsuarios();
        tabelaUsuarios.setModel(modelo);
     }
       
     
     public void excluirUsuario(){
      try {
            int linhaSelecionada = tabelaUsuarios.getSelectedRow();
            if (linhaSelecionada != -1) {
                Usuario usuarioSelecionado = usuarios.get(linhaSelecionada);

                int resposta;
                String mensagem = "Desseja excluir o usuario " + usuarioSelecionado.getNome()+"?";
                String titulo = "Exclusão de usuario";
                resposta = JOptionPane.showConfirmDialog(this, mensagem, titulo, JOptionPane.YES_NO_OPTION);

                if (resposta == JOptionPane.YES_NO_OPTION) {
                    UsuarioBO usuarioBO = new UsuarioBO();
                    usuarioBO.excluirUsuario(usuarioSelecionado);                             
                    mensagem = "Usuario " + usuarioSelecionado.getNome() + " Id: " + usuarioSelecionado.getId() + " excluído com sucesso!";
                    JOptionPane.showMessageDialog(this, mensagem, "Exclusão de Usuário", JOptionPane.INFORMATION_MESSAGE);
                    this.carregarTabelaDeUsuarios();
                }

            } else {
                String mensagem = "Selencione uma usuarios antes.";
                JOptionPane.showMessageDialog(this, mensagem, "Exclusão de Usuário", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (SQLException s) {
           
        }   
     }     
     
     public void editarUsuario(){         
         int linhaSelecionada = tabelaUsuarios.getSelectedRow();
         if (linhaSelecionada != -1) {
             Usuario usuarioSelecionado = usuarios.get(linhaSelecionada);
             if (this.telaDeUsuarios == null) {
                 this.telaDeUsuarios = new TelaDeUsuarios(usuarioSelecionado, this.estadoTela, this );
             }
             this.telaDeUsuarios.setVisible(true);
             this.telaDeUsuarios.toFront();
         } else {
             String mensagem = "Selencione uma usuarios antes.";
             JOptionPane.showMessageDialog(this, mensagem, "Exclusão de Usuário", JOptionPane.INFORMATION_MESSAGE);
         }
     }   
            
       private void exibeGrupoTrabalho() {
           jList1.setListData(new Vector());
        int linhaSelecionada = tabelaUsuarios.getSelectedRow();
        if (linhaSelecionada != -1) {
             Usuario usuarioSelecionado = usuarios.get(linhaSelecionada);
             gruposTrabalho = usuarioSelecionado.getGrupoUsuario();
             
             DefaultListModel dlm = new DefaultListModel();
             Iterator it = gruposTrabalho.iterator();
             while (it.hasNext()) {
                dlm.addElement(it.next());
             }                
             jList1.setModel(dlm);
        }else{
           String mensagem = "Selencione uma usuarios antes.";
           JOptionPane.showMessageDialog(this, mensagem, "Exclusão de Usuário", JOptionPane.INFORMATION_MESSAGE);
         
        }
    }
     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCargos;
    private javax.swing.JButton btnEditarUsuario;
    private javax.swing.JButton btnExcluirUsuario;
    private javax.swing.JButton btnNovoUsuario;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable tabelaUsuarios;
    // End of variables declaration//GEN-END:variables

 //classe interna
    private class ModeloTabelaUsuarios extends AbstractTableModel {
        @Override
        public String getColumnName(int coluna) {
            if(coluna == 0){
                return "Nome";
            } else if(coluna == 1) {
                return "Login";
            }else if(coluna == 2) {
                return "Senha";
            }
            return null;
        }   
        
        @Override
        public int getRowCount() {
            return usuarios.size();
        }
        
        @Override
        public int getColumnCount() {
            return 3;
        }
        
        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
            Usuario usuario = usuarios.get(rowIndex);
            if (columnIndex == 0) {
                return usuario.getNome();
            } else if (columnIndex == 1) {
                return usuario.getLogin();
            } else if(columnIndex == 2){
                return usuario.getSenha();
            } else{
                return null;
           } 
        }

    }
}
